### PR TITLE
Refactor styles, add variable to adjust heading color

### PR DESCRIPTION
**Pull request by deiteris**
1. Use heading variables in the `.section.endpoints-title` class.
2. Add the `--api-summary-endpoint-path-font-weight` variable to control font weight of the `.endpoint-path` class.
3. Add `--arc-font-subhead-color` to allow heading color modification.

### CODE REVIEW

**Review by jarrodek — DISMISSED** [review]
LGTM but, please, don't merge until @TwoPlusTwoOne confirms it is safe to change CSS vars.

**Comment by deiteris** [comment]
> LGTM but, please, don't merge until @TwoPlusTwoOne confirms it is safe to change CSS vars.

But variables were not changed in this PR. I only added new variables and used existing ones.

**Review by twoplustwoone — DISMISSED** [review]
Everything LGTM

**Comment by deiteris** [comment]
Force-pushed same commits with signature.

**Pull request merged**
